version: '3.4'

services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app/
    ports:
      - 5000:5000
    links:
      - db
    depends_on:
      - db
    container_name: frontmen_test_api
  db:
    image: mongo:latest
    container_name: frontmen_test_db
    ports:
      - 27017:27017
  frontend:
    build: ./frontend
    ports:
      - 80:80
    environment:
      - API_URL=http://localhost:5000